version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: skillex_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-skillex_db}
      MYSQL_USER: ${MYSQL_USER:-skillex_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-skillex_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - skillex_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  skillex_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
